spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ThePassword
    url: jdbc:mysql://192.168.1.11:3306/tacoRebuild
    username: springuser
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
taco:
  orders:
    maxCountLastOrders: 10
bean-var:
  valueOne: 100