spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ThePassword
    url: jdbc:mysql://192.168.1.11:3306/YOUstart
    username: springuser
  jpa:
    hibernate:
      ddl-auto: update
upload:
  path: /s:/Файлы на время/YOUstart/upload